version: 2
jobs:
  project_setup:
    docker:
      - image: circleci/node:10.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths: .
  project_react_test:
    docker:
      - image: circleci/node:10.9.0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Set up NPM to use circleci user
          command: npm set prefix=/home/circleci/npm && echo 'export PATH=/home/circleci/npm/bin:$PATH' >> /home/circleci/.bashrc
      - run:
          name: Install dependencies and link project
          command: |
            npm i
            npm link
      - save_cache:
          key: npm-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Install yeoman
          command: npm i -g yo
      - run:
          name: Generate React project, run tests and build
          command: |
            mkdir /home/circleci/client && cd "$_"
            /home/circleci/npm/bin/yo theodo-stack:react --empty-folder
            npm run test
            npm run build
            npm run flow:coverage
      - run:
          name: Install Snyk
          command: npm i -g snyk
      - run:
          name: Test module dependencies
          command: |
            /home/circleci/npm/bin/snyk auth ${SNYK_TOKEN}
            /home/circleci/npm/bin/snyk ignore --id='shelljs@0.8.2' --expiry='2019-01-01' --reason='testing'
            /home/circleci/npm/bin/snyk test --severity-threshold=high

workflows:
  version: 2
  build_setup_test:
    jobs:
      - project_setup
      - project_react_test:
          requires:
            - project_setup
