version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - './devops/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - 80:80
    depends_on:
      - client
      - server
  client:
    build: .
    volumes:
      - '.:/code:cached'  # cached options is used for performance: https://docs.docker.com/docker-for-mac/osxfs-caching/#cached
    command: 'yarn client:watch'
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
      - 35729:35729
  server:
    build: .
    volumes:
      - '.:/code:cached' # cached options is used for performance: https://docs.docker.com/docker-for-mac/osxfs-caching/#cached
    command: 'yarn server:watch'
    ports:
      - 9229:9229
    depends_on:
      - postgresql
    environment:
      - NODE_ENV=development
  postgresql:
    image: 'postgres:9.6'
    environment:
      - POSTGRES_USER=<%= appName %>
      - POSTGRES_PASSWORD=<%= appName %>
      - POSTGRES_DB=<%= appName %>
